export const toasts = [
    "Well done!",
    "Well done!!",
    "Fantastic!",
    "Bravo!",
    "On to the next challenge!",
    "Nailed it!",
    "Masterfully mixed!",
    "Hue did it!",
    "A hue-mongous victory!",
    "Blend it like a boss!",
    "Next level, please!",
    "Pigment prodigy!",
    "Let's continue!",
    "Tonal triumph!",
    "Color-tastic!",
    "Next level, here we come!",
    "Blend-tastic!",
    "Next level awaits!",
    "Hue nailed it!",
];
